version: '3'
services:
  js_boi:
    build:
      context: ./serverJs
    ports:
      - "6000:6000"
    env_file:
      - ./serverJs/.env

  python_boi:
    build:
      context: ./serverPython
    ports:
      - "5000:5000"
    env_file:
      - ./serverPython/.env

  client_boi:
    build:
      context: ./client
    ports:
      - "3000:3000"
