version: '3.9'
services:
  server1:
    build: ./serverPython
    ports:
    - "5000:5000"
    volumes:
    - ./serverPython:/app
    environment:
      FLASK_ENV: development
  server2:
    build: ./serverJs
    ports:
    - "6000:6000"
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server1
