apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientapp
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - name: clientapp-container
        image: ams132/clientapp
