apiVersion: v1
kind: Service
metadata:
  name: serverjs-service
spec:
  type: NodePort
  selector:
    app: serverjs
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 31000