apiVersion: v1
kind: Service
metadata:
  name: serverpython-service
spec:
  type: NodePort
  selector:
    app: serverpython
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000